auth_login:
    path: /api/login
    controller: App\Controller\Api\AuthController::login
    methods: [POST]

auth_logout:
    path: /api/logout
    controller: App\Controller\Api\AuthController::logout
    methods: [POST]

auth_register:
    path: /api/register
    controller: App\Controller\Api\AuthController::register
    methods: [POST]

auth_update:
    path: /api/auth/update
    controller: App\Controller\Api\AuthController::update
    methods: [PUT]

auth_info:
    path: /api/auth/info
    controller: App\Controller\Api\AuthController::user
    methods: [GET]

